ls:
  .js: kebab-case | camelCase
  .ts: kebab-case | camelCase
  .d.ts: kebab-case
  .config.js: kebab-case
  .umd.js: kebab-case
  .spec.ts: point.case

  .\dist\**:
    .js: point.case

ignore:
  - node_modules
  - .git
  - .circleci
  - .github
  - .vscode
  - .idea
  - .\@config
  - .\.eslintrc.js
